import json,html,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2];OUT=ROOT/'pages/coding-lab';data=json.loads((ROOT/'tools/coding-lecture/content.json').read_text());esc=lambda s:html.escape(str(s));br=lambda s:esc(s).replace('\n','<br>')
slides=[]
for i,s in enumerate(data['slides'],1):
 if i==1:
  slides.append((ROOT/'tools/coding-lecture/intro.html').read_text());continue
 content=''
 if s.get('quote'):content+=f'<blockquote data-reveal>{br(s["quote"])}</blockquote><p class="caption">{esc(s["caption"])}</p>'
 if s.get('lead'):content+=f'<p class="lead" data-reveal>{br(s["lead"])}</p>'
 if s.get('visual'):content+=f'<div class="word-path" data-reveal>{esc(s["visual"])}</div>'
 if s.get('items'):
  content+='<div class="items">'+''.join(f'<div class="item" data-reveal><span class="item-label">{br(a)}</span><p>{br(b)}</p></div>' for a,b in s['items'])+'</div>'
 if s.get('prompt'):content+=f'<div class="prompt-body" data-reveal><p class="prompt-text">{br(s["prompt"])}</p><button type="button" data-copy>이 문장 복사</button><span class="copy-status" role="status"></span></div>'
 if s.get('companion'):
  c=s['companion'];content+='<aside class="companion" data-reveal><p class="companion-heading">'+esc(c['title'])+'</p>'+''.join('<div class="companion-row"><span>'+esc(a)+'</span><p>'+esc(b)+'</p></div>' for a,b in c['items'])+'</aside>'
 if s.get('image'):content+=f'<figure data-reveal><img src="{esc(s["image"])}" alt="차근차근 샘플 읽기 화면. 먼저 뜻을 읽고 결과를 펼치는 구조." width="1400" height="1000"><figcaption>{esc(s["caption"])}</figcaption></figure>'
 if s.get('link'):content+=f'<a class="slide-link" href="{esc(s["link"]["url"])}" target="_blank" rel="noreferrer">{esc(s["link"]["label"])}</a>'
 if s.get('takeaway'):content+=f'<p class="takeaway" data-reveal>{esc(s["takeaway"])}</p>'
 slides.append(f'<section class="slide kind-{s["kind"]} theme-{s["theme"]} {"has-companion" if s.get("companion") else ""}" id="slide-{i}" aria-labelledby="title-{i}"><p class="eyebrow">{esc(s["chapter"])} <span>Mirinaeman Coding</span></p><div class="title-block"><h2 id="title-{i}" tabindex="-1">{br(s["title"])}</h2></div><div class="scene-body">{content}</div><span class="slide-number">{i:02} / 30</span><aside class="speaker-notes">{esc(s["notes"])}</aside></section>')
options=''.join(f'<option value="{i-1}">{i:02} {esc(s["title"].replace(chr(10)," "))}</option>' for i,s in enumerate(data['slides'],1))
ld={"@context":"https://schema.org","@type":"WebPage","name":data['title'],"description":data['subtitle'],"url":data['canonical'],"inLanguage":"ko","learningResourceType":"강의 웹 프리젠테이션","author":{"@type":"Person","name":data['author']},"image":data['canonical']+'assets/og.webp'}
page=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(data['title'])} | 미리내맨 코딩</title><meta name="description" content="{esc(data['subtitle'])}"><link rel="canonical" href="{data['canonical']}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(data['title'])}"><meta property="og:description" content="{esc(data['subtitle'])}"><meta property="og:url" content="{data['canonical']}"><meta property="og:image" content="{data['canonical']}assets/og.webp"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/webp"><meta property="og:image:alt" content="내 생각을 작동하는 앱으로, 미리내맨 코딩 강의"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(data['title'])}"><meta name="twitter:description" content="{esc(data['subtitle'])}"><meta name="twitter:image" content="{data['canonical']}assets/og.webp"><meta name="twitter:image:alt" content="내 생각을 작동하는 앱으로, 미리내맨 코딩 강의"><meta name="theme-color" content="#020202"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="intro.css"><script type="application/ld+json">{json.dumps(ld,ensure_ascii=False)}</script></head><body><a class="skip" href="#presentation">본문으로</a><header class="toolbar"><a href="https://mirinaeman.com/">미리내맨</a><span class="deck-title">내 생각을, 작동하는 앱으로</span><div><button id="share">공유</button><button id="reading" aria-pressed="false">읽기 모드</button><button id="fullscreen">전체 화면</button></div></header><h1 class="sr-only">내 생각을, 작동하는 앱으로 — 미리내맨 코딩 강의</h1><main id="presentation" aria-label="미리내맨 코딩 강의 30장"><div class="viewport"><div class="stage">{''.join(slides)}</div></div></main><footer class="controls"><button id="prev">이전</button><label class="sr-only" for="jump">슬라이드 선택</label><select id="jump">{options}</select><span id="position" role="status" aria-live="polite">1 / 30</span><button id="notes-toggle" aria-expanded="false">강의 해설</button><button id="next">다음</button></footer><div class="progress" aria-hidden="true"><span></span></div><section id="notes-panel" hidden aria-label="현재 슬라이드 강의 해설"><h2>강의 해설</h2><p></p><p class="small">공개 심사와 실제 개인 PDF·유료 AI 검증 상태는 강의 작성 시점 기준입니다. 최신 상태는 앱과 플러그인 안내에서 확인하세요.</p></section><p class="sr-only" id="share-status" role="status"></p><noscript><p>스크립트가 꺼져 있어 모든 슬라이드를 순서대로 표시합니다.</p></noscript><script src="presentation.js" defer></script></body></html>'''
OUT.mkdir(parents=True,exist_ok=True);(OUT/'index.html').write_text(page);(OUT/'sitemap.xml').write_text(f'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>{data["canonical"]}</loc></url></urlset>');(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+data['canonical']+'sitemap.xml\n');print('Built',len(slides),'slides')
