"""Tuna introduction derived from the public catalog; no Work-menu insertion."""
import json,html,argparse
from pathlib import Path
from context_graph import prose
R=Path(__file__).resolve().parents[1];P=R/'pages/profile';B='tuna-man';U='https://mirinaeman.com/archive/tuna-man/'
def render():
 catalog={x['body_id']:x for x in json.loads((P/'data/message-bodies.json').read_text())['bodies']};b=catalog[B];c=json.loads((P/'data/tuna-context.json').read_text());profile=json.loads((P/'data/creator-profile.json').read_text());pid=profile['url']+'#person';title=b['title']+' — 신나는 펑크록 자기소개';desc=b['message_sentence'];og=U+'assets/og.jpg';e=html.escape
 related=[{**x,**catalog[x['body_id']], 'link_url': 'https://mirinaeman.com'+x['intro_path'] if x.get('intro_path') else catalog[x['body_id']]['canonical_url']} for x in c['related']]
 graph={'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':U,'url':U,'name':title,'description':desc,'mainEntity':{'@id':b['canonical_url']+'#song'},'author':{'@id':pid},'relatedLink':[b['canonical_url'],*[x['link_url'] for x in related]]},{'@type':'Person','@id':pid,'name':profile['name'],'alternateName':'미리내맨','url':profile['url']},{'@type':'CreativeWork','@id':b['canonical_url']+'#song','url':b['canonical_url'],'name':b['title'],'description':desc,'creator':{'@id':pid}},*[{'@type':'CreativeWork','url':x['canonical_url'],'name':x['title'],'description':x['reason']} for x in related]]}
 head='<meta name="description" content="'+e(desc)+'"><link rel="canonical" href="'+U+'">'
 for key,val in {'type':'website','title':title,'description':desc,'url':U,'image':og,'image:type':'image/jpeg','image:width':'1200','image:height':'630','image:alt':b['thumbnail']['alt']}.items():head+='<meta property="og:'+key+'" content="'+e(val)+'">'
 for key,val in {'card':'summary_large_image','title':title,'description':desc,'image':og,'image:alt':b['thumbnail']['alt']}.items():head+='<meta name="twitter:'+key+'" content="'+e(val)+'">'
 related_html=''.join('<h3 data-typography-break="approved">'+prose(x['title'])+'</h3><p>'+prose(x['reason'])+'</p><p><a href="'+x['link_url']+'"'+(' target="_blank" rel="noopener noreferrer"' if not x['link_url'].startswith('https://mirinaeman.com/') else '')+'>'+e(x['title'])+(' 소개 읽기' if x.get('intro_path') else ' 감상하기 ↗')+'</a></p>' for x in related)
 return f'''<!doctype html><html lang="ko" data-lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title>{head}<meta name="robots" content="index,follow,max-image-preview:large"><meta name="site-home" content="https://mirinaeman.com/"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="../image-cinema/context.css"><script type="application/ld+json">{json.dumps(graph,ensure_ascii=False)}</script><script defer src="../../navigation.js"></script><script defer src="../../app.js"></script><script defer src="../jeju-we/share.js"></script></head><body><a class="skip" href="#main">본문으로 이동</a><site-navigation data-page="archive"></site-navigation><main id="main"><section class="page-hero"><div class="wrap"><span class="eyebrow">FUNK ROCK · WEBTOON · IMAGE CINEMA</span><h1>{e(b['title'])}</h1><div class="context-prose"><p>{prose(desc)}</p><p>노래와 창작 · <a href="{profile['url']}">미리내맨</a></p></div><div class="actions"><a class="button primary" href="{b['canonical_url']}">노래·웹툰·시네마 감상하기 ↗</a><button class="button" type="button" id="share-page">페이지 공유</button></div><p id="share-status" role="status"></p></div></section><section class="section"><div class="wrap context-prose"><figure><img src="assets/og.jpg" width="1200" height="630" style="max-width:100%;height:auto" alt="{e(b['thumbnail']['alt'])}"></figure><h2>폼은 대부 — 발끝은 둠칫</h2><p>{prose(c['origin'])}</p><h2>그게 바로 나다</h2><p>{prose(c['music'])}</p><h2>같은 사나이를 만나는 세 가지 시간</h2><p>{prose(c['media'])}</p><p>음악 · mirinaeman / Suno로 제작<br>원화 · AI 생성 이미지</p><div class="actions"><a class="button primary" href="{b['canonical_url']}">감상 시작 ↗</a></div></div></section><section class="section"><div class="wrap context-prose"><h2>이어지는 작품</h2>{related_html}<p><a href="https://mirinaeman.com/archive/image-cinema/">창작노트</a>에서 노래와 이미지 사이의 관계를 더 읽을 수 있습니다</p></div></section></main><footer class="footer"><div class="wrap"><p>© 미리내맨 · mirinaeman.com</p><a href="https://mirinaeman.com/archive/">전체 아카이브</a></div></footer></body></html>'''
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--check',action='store_true');args=a.parse_args();p=P/'archive/tuna-man/index.html';s=render()
 if args.check:assert p.read_text()==s,'Tuna introduction drift'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
 print('Tuna introduction: PASS')
