"""Render the archive introduction without adding a Work-menu card."""
import argparse,html,json,re
from pathlib import Path
from public_routes import editorial_url
ROOT=Path(__file__).resolve().parents[1];PROFILE=ROOT/'pages/profile';BODY_ID='baekun-five-strike-action-cinema'
def render():
 catalog=json.loads((PROFILE/'data/message-bodies.json').read_text());b=next(x for x in catalog['bodies'] if x['body_id']==BODY_ID)
 url=editorial_url(BODY_ID);og=url+'assets/og.jpg';title=b['title']+' — 작품 소개';desc=b['message_sentence'];e=html.escape
 graph={'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':url,'url':url,'name':title,'description':desc,'inLanguage':'ko','mainEntity':{'@id':b['canonical_url']+'/#work'},'author':{'@id':'https://mirinaeman.com/#person'}},{'@type':'Person','@id':'https://mirinaeman.com/#person','name':'미리내맨','url':'https://mirinaeman.com/profile/'},{'@type':'CreativeWork','@id':b['canonical_url']+'/#work','name':b['title'],'url':b['canonical_url'],'creator':{'@id':'https://mirinaeman.com/#person'},'isBasedOn':{'@id':'https://mirinaeman.com/pages/hwasan/'}},{'@type':'CreativeWork','@id':'https://mirinaeman.com/pages/hwasan/','name':'화산인수','url':'https://mirinaeman.com/pages/hwasan/','creator':{'@id':'https://mirinaeman.com/#person'}}]}
 return f'''<!doctype html><html lang="ko" data-lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="site-home" content="https://mirinaeman.com/"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url}"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{og}"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="{e(b['thumbnail']['alt'])}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{e(title)}"><meta name="twitter:description" content="{e(desc)}"><meta name="twitter:image" content="{og}"><meta name="twitter:image:alt" content="{e(b['thumbnail']['alt'])}"><script type="application/ld+json">{json.dumps(graph,ensure_ascii=False)}</script><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="reading.css"><script defer src="../../navigation.js"></script><script defer src="../../app.js"></script></head><body><a class="skip" href="#main">본문으로 이동</a><site-navigation data-page="archive"></site-navigation><main id="main"><section class="page-hero"><div class="wrap"><span class="eyebrow">HWASAN INSU · IMAGE CINEMA · WEBTOON</span><h1>{e(b['title'])}</h1><div style="max-width:var(--measure)"><p>{e(desc)}</p><p>원작 · 연출 판단 · <a href="https://mirinaeman.com/profile/">미리내맨 김준호</a></p></div><div class="actions"><a class="button primary" href="{e(b['canonical_url'])}" target="_blank" rel="noopener noreferrer">이미지 시네마 · 웹툰 감상하기</a></div></div></section><section class="section"><div class="wrap"><figure><img src="assets/og.jpg" width="1200" height="630" alt="{e(b['thumbnail']['alt'])}" loading="lazy"></figure></div></section><section class="section"><div class="wrap introduction-copy" style="max-width:var(--measure)"><h2>꽃잎이 닿기 전에</h2><p>백운이 다섯 검객을 돌파합니다.<br>반천운겁과 자하신공의 파문이 지나간 뒤에도 여운은 잔향으로 남습니다.</p><p>이 작품은 미리내맨 김준호의 <a href="https://mirinaeman.com/pages/hwasan/">무협 원작 화산인수</a>를 이미지 시네마로 옮긴 창작입니다.</p><h2>움직임을 채우는 사람</h2><p>정지된 장면과 장면 사이에 여백을 둡니다.<br>보이지 않는 칼의 궤적과 돌파의 순간은 보는 사람의 상상으로 이어집니다.</p><p>33초의 이미지 시네마에는 장면에 맞춰 AI로 제작한 배경음악과 효과음이 함께 흐릅니다.<br>아홉 컷의 웹툰은 독자가 머무르는 속도로 읽습니다.</p><h2>미디어는 메시지의 몸이다</h2><p>맥루언의 쿨미디어 관점에서 출발한 이미지 시네마 실험입니다.<br>음악이 시간을 이끌고 그림의 여백이 관객의 참여를 부릅니다.</p><p>창작자가 말한 “여운이 잔향으로 남아”라는 감각을 영상과 웹툰의 서로 다른 시간으로 만납니다.</p><div class="actions"><a class="button" href="https://mirinaeman.com/archive/">아카이브로</a></div></div></section></main><footer class="footer"><div class="wrap"><p>© 미리내맨 · mirinaeman.com</p></div></footer></body></html>'''
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=PROFILE/'archive'/BODY_ID/'index.html';content=render()
 content=re.sub(r'<p([^>]*)>(.*?)</p>',lambda m:'<p'+m[1]+'><span class="statement-line">'+m[2].replace('<br>','</span><span class="statement-line">')+'</span></p>',content,flags=re.S)
 if a.check:assert p.read_text()==content,'Hwasan Returning Clouds introduction drift'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)
 print('Hwasan Returning Clouds introduction: PASS')
