"""Generate the presentation's readable archive introduction from the public catalog."""
import argparse,html,json
from pathlib import Path
from context_graph import prose
R=Path(__file__).resolve().parents[1];P=R/'pages/profile';B='harugyeol-ai-health';U='https://mirinaeman.com/archive/'+B+'/'
def render():
 catalog={x['body_id']:x for x in json.loads((P/'data/message-bodies.json').read_text())['bodies']};b=catalog[B];c=json.loads((P/'data/harugyeol-context.json').read_text());person=json.loads((P/'data/creator-profile.json').read_text());pid=person['url']+'#person';title=b['title']+' | 웹 프레젠테이션 제작 사례';desc=b['message_sentence'];og=U+'assets/og.jpg';e=html.escape
 related=[{**catalog[x['body_id']], 'reason':x['reason']} for x in c['related']]
 graph={'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':U,'url':U,'name':title,'description':desc,'inLanguage':'ko','mainEntity':{'@id':b['canonical_url']+'#presentation'},'author':{'@id':pid},'relatedLink':[b['canonical_url'],*[x['canonical_url'] for x in related]]},{'@type':'Person','@id':pid,'name':person['name'],'alternateName':'미리내맨','url':person['url']},{'@type':'CreativeWork','@id':b['canonical_url']+'#presentation','url':b['canonical_url'],'name':b['title'],'description':desc,'creator':{'@id':pid},'learningResourceType':'슬라이드','educationalUse':'교육','subjectOf':{'@id':U}},*[{'@type':'CreativeWork','url':x['canonical_url'],'name':x['title'],'description':x['reason']} for x in related]]}
 head='<meta name="description" content="'+e(desc)+'"><link rel="canonical" href="'+U+'">'
 for key,val in {'type':'website','title':title,'description':desc,'url':U,'image':og,'image:type':'image/jpeg','image:width':'1200','image:height':'630','image:alt':b['thumbnail']['alt']}.items():head+='<meta property="og:'+key+'" content="'+e(val)+'">'
 for key,val in {'card':'summary_large_image','title':title,'description':desc,'image':og,'image:alt':b['thumbnail']['alt']}.items():head+='<meta name="twitter:'+key+'" content="'+e(val)+'">'
 outline=''.join('<li><strong>'+e(t)+'</strong><p>'+prose(d)+'</p></li>' for t,d in c['outline'])
 more=''.join('<h3>'+e(x['title'])+'</h3><p>'+prose(x['reason'])+'</p><p><a href="'+e(x['canonical_url'])+'">'+e(x['title'])+' 열기 ↗</a></p>' for x in related)
 return f'''<!doctype html><html lang="ko" data-lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title>{head}<meta name="robots" content="index,follow,max-image-preview:large"><meta name="site-home" content="https://mirinaeman.com/"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="../image-cinema/context.css"><script type="application/ld+json">{json.dumps(graph,ensure_ascii=False)}</script><script defer src="../../navigation.js"></script><script defer src="../../app.js"></script><script defer src="../jeju-we/share.js"></script></head><body><a class="skip" href="#main">본문으로 이동</a><site-navigation data-page="archive"></site-navigation><main id="main"><section class="page-hero"><div class="wrap"><span class="eyebrow">AI · EDUCATION · WEB PRESENTATION</span><h1>{e(b['title'])}</h1><div class="context-prose"><p>{prose(desc)}</p><p>기획·제작 · <a href="{person['url']}">김준호 · 미리내맨</a></p></div><div class="actions"><a class="button primary" href="{b['canonical_url']}">15장 프레젠테이션 열기 ↗</a><button class="button" type="button" id="share-page">페이지 공유</button></div><p id="share-status" role="status"></p></div></section><section class="section"><div class="wrap context-prose"><figure><img src="assets/og.jpg" width="1200" height="630" style="max-width:100%;height:auto" alt="{e(b['thumbnail']['alt'])}"></figure><h2>한 사람의 더 나은 하루에서 시작하기</h2><p>{prose(c['origin'])}</p><h2>직접 움직이며 보는 발표</h2><p>{prose(c['experience'])}</p><h2>애니메이션 다음에 남는 것은 레이아웃</h2><p>{prose(c['judgment'])}</p><h2>15장의 발표 내용</h2><ol>{outline}</ol><p>{prose(c['boundary'])}</p><div class="actions"><a class="button primary" href="{b['canonical_url']}">프레젠테이션 시작 ↗</a></div></div></section><section class="section"><div class="wrap context-prose"><h2>이어지는 작품</h2>{more}<p><a href="https://mirinaeman.com/constellation/?node=work%3Aharugyeol-ai-health">미리내의 별자리에서 관계 살펴보기</a></p></div></section></main><footer class="footer"><div class="wrap"><p>© 미리내맨 · mirinaeman.com</p><a href="https://mirinaeman.com/archive/">전체 아카이브</a></div></footer></body></html>'''
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args();path=P/'archive'/B/'index.html';content=render()
 if args.check:assert path.read_text()==content,'Harugyeol introduction drift'
 else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
 print('Harugyeol introduction: PASS')
