"""Render the WE travel introduction from its editorial export and body catalog."""
import argparse,html,json,re
from pathlib import Path
from public_routes import editorial_url
ROOT=Path(__file__).resolve().parents[1]; PROFILE=ROOT/'pages/profile'
def render():
 d=json.loads((PROFILE/'data/jeju-we-visit.json').read_text()); b=next(x for x in json.loads((PROFILE/'data/message-bodies.json').read_text())['bodies'] if x['body_id']=='jeju-we')
 e=html.escape;url=editorial_url('jeju-we');view=d['viewingUrl'].rstrip('/')+'/';og=url+'assets/og.png';person=d['creatorUrl']+'#person';work=view+'#work';hotel=d['officialUrl']+'#hotel'
 graph={'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':url,'url':url,'name':d['title'],'description':d['description'],'inLanguage':'ko','author':{'@id':person},'mainEntity':{'@id':work},'relatedLink':view},{'@type':'Person','@id':person,'name':d['creator'],'url':d['creatorUrl']},{'@type':'CreativeWork','@id':work,'url':view,'name':'제주 WE 호텔 부부 여행 — 당신과 나, 다시 우리','creator':{'@id':person},'about':{'@id':hotel},'hasPart':[{'@id':view+'#recording'},{'@id':view+'#webtoon'},{'@id':view+'cinema#video'}]},{'@type':'Hotel','@id':hotel,'name':d['hotelName'],'url':d['officialUrl'],'telephone':d['telephone'],'hasMap':d['embedUrl'],'address':{'@type':'PostalAddress','streetAddress':'1100로 453-95','addressLocality':'서귀포시','addressRegion':'제주특별자치도','addressCountry':'KR'}}]}
 def a(key,label):return f'<a class="button" href="{e(d[key])}" target="_blank" rel="noopener noreferrer">{label}</a>'
 meta=''.join(f'<meta {kind}="{key}" content="{e(value)}">' for kind,key,value in [('name','description',d['description']),('name','robots','index,follow,max-image-preview:large'),('property','og:type','website'),('property','og:title',d['title']),('property','og:description',d['description']),('property','og:url',url),('property','og:image',og),('property','og:image:type','image/png'),('property','og:image:width','1200'),('property','og:image:height','630'),('property','og:image:alt',d['imageAlt']),('name','twitter:card','summary_large_image'),('name','twitter:title',d['title']),('name','twitter:description',d['description']),('name','twitter:image',og),('name','twitter:image:alt',d['imageAlt'])])
 return f'''<!doctype html>
<html lang="ko" data-lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="site-home" content="https://mirinaeman.com/"><title>{e(d['title'])}</title>{meta}<link rel="canonical" href="{url}"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><script type="application/ld+json">{json.dumps(graph,ensure_ascii=False).replace('<','&lt;')}</script><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="visit.css"><script defer src="../../navigation.js"></script><script defer src="../../app.js"></script></head>
<body><a class="skip" href="#main">본문으로 이동</a><site-navigation data-page="archive"></site-navigation><main id="main"><section class="page-hero"><div class="wrap"><span class="eyebrow">TRAVEL · MUSIC · WEBTOON · IMAGE CINEMA</span><h1>제주 WE, 당신과 나, 다시 우리</h1><div style="max-width:var(--measure)"><p>{e(d['description'])}</p><p>여행 기록 · 노래 원작 <a href="{e(d['creatorUrl'])}">{e(d['creator'])}</a></p></div><div class="actions"><a class="button primary" href="{e(view)}">노래 · 웹툰 · 시네마 감상하기</a><button class="button" type="button" id="share-page">페이지 공유</button></div><p id="share-status" role="status"></p></div></section>
<section class="section"><div class="wrap"><figure><img src="assets/og.png" width="1200" height="630" alt="{e(d['imageAlt'])}" loading="lazy"></figure></div></section>
<section class="section"><div class="wrap visit-story" style="max-width:var(--measure)"><h2>둘만의 휴가, 다시 서른다섯의 마음</h2><p>오랜만에 아내와 단둘이 제주 WE 호텔로 휴가를 떠났습니다.<br>좋은 호텔과 경치, 시설, 산책길, 새소리가 들리는 풍경.<br>멀리 제주 바다가 보이는 뷰까지 좋아서 호텔 주변에서 푹 쉬다 왔습니다.</p><p>그 시간에는 30대로 돌아간 느낌이 들었습니다.<br>그 감정을 노래로 만들고 직접 찍은 사진과 함께 기록했습니다.</p><h2>하나의 마음이 여러 미디어로</h2><p>실제 방문 사진과 숲길 영상은 그곳에서 본 풍경을 전합니다.<br>원곡은 함께 쉰 시간의 감정을 목소리와 리듬으로 담습니다.</p><p>실사 영화풍 웹툰은 다시 젊어진 듯한 마음을 30대 가상 부부의 이야기로 각색했습니다.<br>인물은 실제 부부의 초상이 아닙니다.<br>8장의 스크롤 웹툰을 각자의 속도로 읽을 수 있습니다.</p><p>이미지 시네마는 원곡 전체와 8장면을 약 3분 18초의 시간으로 엮습니다.<br>별도 한국어 가사 자막을 켜고 끌 수 있으며 전체 페이지와 시네마를 각각 공유할 수 있습니다.</p><p>미디어는 메시지의 몸입니다.<br>이 작품은 개인의 휴가에서 느낀 감정이 감상과 공유, 장소에 대한 관심과 찾아가기로 이어지는 두 번째 실험입니다.</p><div class="actions"><a class="button primary" href="{e(view)}cinema">이미지 시네마 감상하기</a><a class="button" href="https://mirinaeman.com/archive/noreut-galchi-album/">첫 번째 실험, 제주 노릇</a></div>
<h2>이야기 속 장소, WE 호텔 제주</h2><p>{e(d['address'])}<br>대표전화 <a href="tel:{e(d['telephone'])}">064-730-1200</a></p><iframe class="visit-map" src="{e(d['embedUrl'])}" title="WE 호텔 제주 위치 지도" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><div class="actions">{a('directionsUrl','호텔 길찾기')}{a('locationUrl','공식 교통 · 셔틀 안내')}{a('officialUrl','호텔 공식 홈페이지')}</div><p>미리내맨의 개인 방문 경험에서 출발한 창작 기록입니다.<br>교통과 셔틀 등 방문 정보는 호텔 공식 안내에서 최신 내용을 확인하세요.</p><div class="actions"><a class="button" href="https://mirinaeman.com/archive/">아카이브로</a></div></div></section></main><footer class="footer"><div class="wrap"><p>© 미리내맨 · mirinaeman.com</p></div></footer><script src="share.js" defer></script></body></html>'''
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=PROFILE/'archive/jeju-we/index.html';content=render()
 content=re.sub(r'<p([^>]*)>(.*?)</p>',lambda m:'<p'+m[1]+'><span class="statement-line">'+m[2].replace('<br>','</span><span class="statement-line">')+'</span></p>',content,flags=re.S)
 if a.check:assert p.read_text()==content,'WE introduction drift'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)
 print('WE archive introduction: PASS')
