"""Render the archive introduction without adding a Work-menu card."""
import argparse,html,json,re
from pathlib import Path
from public_routes import editorial_url
ROOT=Path(__file__).resolve().parents[1];PROFILE=ROOT/'pages/profile';BODY_ID='dont-you-want-my-money'
def render():
 catalog=json.loads((PROFILE/'data/message-bodies.json').read_text());b=next(x for x in catalog['bodies'] if x['body_id']==BODY_ID)
 url=editorial_url(BODY_ID);og=url+'assets/og.jpg';title=b['title']+' — 미리내맨';desc=b['message_sentence'];e=html.escape
 graph={'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':url,'url':url,'name':title,'description':desc,'inLanguage':'ko','mainEntity':{'@id':b['canonical_url']+'/#work'},'author':{'@id':'https://mirinaeman.com/#person'}},{'@type':'Person','@id':'https://mirinaeman.com/#person','name':'미리내맨','url':'https://mirinaeman.com/profile/'},{'@type':'CreativeWork','@id':b['canonical_url']+'/#work','name':b['title'],'url':b['canonical_url'],'creator':{'@id':'https://mirinaeman.com/#person'}},{'@type':'MusicRecording','@id':b['canonical_url']+'/#song','name':b['title'],'byArtist':{'@id':'https://mirinaeman.com/#person'},'url':b['canonical_url']}]}
 return f'''<!doctype html><html lang="ko" data-lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="site-home" content="https://mirinaeman.com/"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url}"><link rel="icon" href="../../favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{og}"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="{e(b['thumbnail']['alt'])}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{e(title)}"><meta name="twitter:description" content="{e(desc)}"><meta name="twitter:image" content="{og}"><meta name="twitter:image:alt" content="{e(b['thumbnail']['alt'])}"><script type="application/ld+json">{json.dumps(graph,ensure_ascii=False)}</script><link rel="stylesheet" href="../../styles.css"><script defer src="../../navigation.js"></script><script defer src="../../app.js"></script></head><body><a class="skip" href="#main">본문으로 이동</a><site-navigation data-page="archive"></site-navigation><main id="main"><section class="page-hero"><div class="wrap"><span class="eyebrow">MUSIC · IMAGE CINEMA · WEBTOON</span><h1>{e(b['title'])}</h1><div style="max-width:var(--measure)"><p>{e(desc)}</p><p>노래 원작 · <a href="https://mirinaeman.com/profile/">미리내맨</a></p></div><div class="actions"><a class="button primary" href="{e(b['canonical_url'])}" target="_blank" rel="noopener noreferrer">노래 · 영상 · 웹툰 감상하기</a></div></div></section><section class="section"><div class="wrap"><figure><img src="assets/og.jpg" width="1200" height="630" alt="{e(b['thumbnail']['alt'])}" loading="lazy"></figure></div></section><section class="section"><div class="wrap" style="max-width:var(--measure)"><h2>이름은 오픈인데</h2><p>공짜를 달라는 것도 아닌 손님이 닫힌 문 앞에 섰습니다.<br>황당해서 화를 내고 돌아서려다가 다시 화면을 눌러 봅니다.</p><p>“내 돈도 안 받냐”라는 질문은 어느새 기다리는 자신을 향합니다.</p><p>노래와 이미지 시네마는 같은 시간을 함께 흐릅니다.<br>웹툰 8장은 읽는 사람의 속도로 이어집니다.</p><p>영상의 가사는 별도 자막으로 표시되며 감상자가 켜고 끌 수 있습니다.</p><h2>작품에 대하여</h2><p>가상의 OPEN 상점을 무대로 한 풍자입니다.<br>샘 알트만의 등장은 창작적 각색이며 실제 발언을 재현하지 않습니다.</p><div class="actions"><a class="button" href="https://mirinaeman.com/archive/">아카이브로</a></div></div></section></main><footer class="footer"><div class="wrap"><p>© 미리내맨 · mirinaeman.com</p></div></footer></body></html>'''
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();p=PROFILE/'archive'/BODY_ID/'index.html';content=render()
 content=re.sub(r'<p([^>]*)>(.*?)</p>',lambda m:'<p'+m[1]+'><span class="statement-line">'+m[2].replace('<br>','</span><span class="statement-line">')+'</span></p>',content,flags=re.S)
 if a.check:assert p.read_text()==content,'Money introduction drift'
 else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)
 print('Money archive introduction: PASS')
